### ISSUE TITLE
Possibly missing Postgresql db schema

### ISSUE THREAD

**Issue by anupamme** [stanfordnlp/chirpycardinal#3] opened 2021-03-12 10:32 UTC
Hello

when I try to import

from agent.agents.local.local_agent import LocalAgent

I get some DB errors. And digging into it:

chirpycardinal/chirpy/response_generators/opinion2/opinion_sql.py

This requires database **twitter_opinions**. And it has some tables e.g. labeled_phrases_cat

However, I could not find the DB schema anywhere in the code or in the instructions.

If I am missing something please point me to that place or if not, could you please specify the schema.

**Comment by anupamme** [comment] 2021-03-18 15:08
I think I misunderstood the installation instructions.

It has to be run as a docker container. However, there are many docker files (Dockerfile) in the codebase so my question would be:

Do I need to just run all the docker containers individually?

Or do I need to select some of the containers? And perhaps is there some coordination required?

If there are some instructions on which docker images to be run, that would be great.

Here is the list of docker files (also I switched to the remote-persistent-agent branch as that was more recent)

/docker/dialogact/Dockerfile
./docker/stanfordnlp/Dockerfile
./docker/g2p/Dockerfile
./docker/qa/Dockerfile
./docker/sentseg/Dockerfile
./docker/gpt2ed/Dockerfile
./docker/questionclassifier/Dockerfile
./docker/convpara1/Dockerfile
./docker/corenlp/Dockerfile
./docker/emotionclassifier/Dockerfile
./docker/coref/Dockerfile
./servers/remote/Dockerfile

Any help would be much appreciated :).

**Comment by AshwinParanjape** [comment] 2021-03-19 18:02
For the "Opinions" response generator (RG), we depend on a database table of opinions scraped from twitter. Without the scraped tweets the RG won't work. If you don't care about that RG as much you can comment it out from the agent. (Also comment out the import from the local_agent). 

If you want to scrape the tweets, you'll fine useful code for that [here](https://github.com/stanfordnlp/chirpycardinal/tree/main/scrapers/twitter). It also contains a python script that initializes the twitter_opinions database. 

The postgres database is not a part of the docker containers. You'll need to host a postgres database locally or on the cloud. It is easy to setup a postgres database locally, so for the purposes of experimentation I would recommend starting there (https://www.postgresql.org/download/). The postgres database is required for music and opinions response generators. But if you want to run the bot without them, you don't need the database. 

If you run the shell_chat.py script, it will take care of building all the docker containers and running them locally (as long as you have docker on your machine). It'll be running all of the dockerfiles that you have listed. 

The remote-persistent-agent branch includes a new agent that connects to remote module urls and persists to a postgres database from turn to turn. We use that in production to serve a chat interface. But that is not necessary for you to run the code locally. However in that branch, I did refactor the code so that the different agents can co-exist and share code. So if you are in that branch, you should be able to run the local agent with `python -m servers.local.shell_chat`. Unfortunately I haven't been able to test if shell chat works on my own computer, which is why I haven't merged the branch with main yet.

**Comment by anupamme** [comment] 2021-03-20 16:33
The commenting of the opinions and also the acknowledgement response generator helped fix the issue.

Also, I reverted back to the main branch.

I am still running into issues when it connects to the elastic search server. I was curious is there a way to test individual services as expected and in that pursuit, I looked at some of the test cases. 

So my question: how to run the test cases? Because that is one way to ensure that all services are running as expected.

**Comment by AshwinParanjape** [comment] 2021-03-20 22:52
The Elastic search service is essential because entity linking depends on it and a lot of response generators will fail without entity linking. 

You can run the test cases by running `sh local_test_integ.sh`. You can modify the command in the [shell script](https://github.com/stanfordnlp/chirpycardinal/blob/main/local_test_integ.sh) to run individual python files or tests. These can be run with unittest or nosetests framework, the shell script uses nosetests.

**Comment by anupamme** [comment] 2021-04-03 20:05
Question on running the docker containers:

when I run python3 shell_chat.py, it tries to build the docker containers and in my case it is failing in the container **stanfordnlp**. The reason is it is not able to **pip install torch**

When I inspected I saw it was trying to download this torch package

Downloading torch-1.5.0-cp37-cp37m-manylinux1_x86_64.whl (752.0 MB)

This downloading fails when I am running on my local MacBook. For some reason it gets killed (still investigating why). But the question is:

However when I install torch without using docker then it installs the following package:

Using cached torch-1.5.0-cp37-none-macosx_10_9_x86_64.whl (80.5 MB)

And I am able to install this package (which is 80MB whereas the other one is 700 MB).

So my question is why is it downloading the Linux torch package (instead of Mac OS package) when using docker? 

Is there some setting in the docker I can change for this?

**Comment by AshwinParanjape** [comment] 2021-04-03 23:54
When you build a docker container, it starts with the docker image supplied in the Dockerfile eg https://github.com/stanfordnlp/chirpycardinal/blob/main/docker/stanfordnlp/Dockerfile. Every dockerfile starts with a docker image, in this case one that is built from `python3.7-slim-buster` (https://github.com/docker-library/python/blob/7217b72192c93ca2033051d7191d5689932d3912/3.7/buster/slim/Dockerfile) which in turn is built from `debian:buster-slim`. So when you do pip install torch, it is going to install the version of torch that is appropriate for debian, in this case manylinux instead of macosx. 

For why the pip install is not working, it could be because the dockerfile and requirements are too old. We built these dockerfiles last summer, they would build then. Or there could be other issues related to disk space or RAM made available to Docker Desktop.

**Comment by AshwinParanjape** [comment] 2021-04-14 23:10
Feel free to reopen this issue if the problem isn't solved.

**Closed by AshwinParanjape** 2021-04-14 23:10 UTC
